# Generated by Django 5.0.14 on 2025-06-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentlysearch',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'ordering': ('id',)},
        ),
    ]
