# Generated by Django 5.0.14 on 2025-06-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_recentlysearch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentlysearch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={},
        ),
    ]
