# Generated by Django 5.2.5 on 2025-09-03 07:24

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_recentlysearch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preference',
            field=core.fields.MSSQLJSONField(default=dict),
        ),
    ]
