# Generated by Django 5.2.5 on 2025-10-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userpreference_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_notif',
            field=models.BooleanField(default=False),
        ),
    ]
