# Generated by Django 5.1.6 on 2025-06-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={},
        ),
        migrations.AlterModelOptions(
            name='costcentercode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='freightforwarder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packagingtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rejectioncode',
            options={},
        ),
    ]
