# Generated by Django 5.1.6 on 2025-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_addressbook_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freightforwarder',
            name='mot',
        ),
        migrations.AddField(
            model_name='freightforwarder',
            name='mot',
            field=models.ManyToManyField(related_name='freight_forwarders', to='portal.mot'),
        ),
    ]
