# Generated by Django 5.1.6 on 2025-06-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_freightforwarder_mot_freightforwarder_mot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Consignment', 'Consignment'), ('Purchase Order', 'Purchase Order'), ('Console', 'Console'), ('Expediting', 'Expediting')], default='Consignment', max_length=20)),
                ('description', models.TextField()),
                ('attachments', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_receivers', models.JSONField(blank=True, default=list, null=True)),
                ('operations_receivers', models.JSONField(blank=True, default=list, null=True)),
                ('supplier_receivers', models.JSONField(blank=True, default=list, null=True)),
                ('client_receivers', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
