# Generated by Django 5.1.6 on 2025-06-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
    ]
