# Generated by Django 5.1.6 on 2025-06-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_notification_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
