# Generated by Django 5.1.6 on 2025-06-18 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Consignment', 'Consignment'), ('Purchase Order', 'Purchase Order'), ('Console', 'Console'), ('Expediting', 'Expediting')], default='Consignment', max_length=20)),
                ('description', models.TextField()),
                ('attachments', models.CharField(blank=True, max_length=255, null=True)),
                ('operations_receivers', models.JSONField(blank=True, default=list, null=True)),
                ('supplier_receivers', models.JSONField(blank=True, default=list, null=True)),
                ('client_receivers', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('operations_archive', models.JSONField(blank=True, default=list, null=True)),
                ('supplier_archive', models.JSONField(blank=True, default=list, null=True)),
                ('client_archive', models.JSONField(blank=True, default=list, null=True)),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='portal.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
