# Generated by Django 5.0.14 on 2025-06-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_notification_archivenotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='archivenotification',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='costcentercode',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='freightforwarder',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='mot',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='packagingtype',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='rejectioncode',
            options={'ordering': ('id',)},
        ),
    ]
