# Generated by Django 5.0.14 on 2025-06-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_addressbook_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={},
        ),
        migrations.AlterModelOptions(
            name='archivenotification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='costcentercode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='freightforwarder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packagingtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rejectioncode',
            options={},
        ),
    ]
