# Generated by Django 5.0.14 on 2025-06-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_addressbook_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DropDownValues',
        ),
    ]
