# Generated by Django 5.0.14 on 2025-06-20 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_delete_dropdownvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropDownValues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dropdown_name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('parent_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='portal.dropdownvalues')),
            ],
            options={
                'unique_together': {('label', 'parent_item')},
            },
        ),
    ]
