# Generated by Django 5.0.14 on 2025-06-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_dropdownvalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagingtype',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='packagingtype',
            name='weight_unit',
        ),
    ]
