# Generated by Django 5.0.14 on 2025-07-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_packagingtype_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingtype',
            name='package_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
