# Generated by Django 5.0.14 on 2025-07-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_client_options_alter_clientuser_options_and_more'),
        ('portal', '0013_alter_packagingtype_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingtype',
            name='package_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='packagingtype',
            unique_together={('package_name', 'supplier')},
        ),
    ]
