# Generated by Django 5.0.14 on 2025-07-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_packagingtype_package_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costcentercode',
            unique_together={('plant_id', 'center_code')},
        ),
    ]
