# Generated by Django 5.0.14 on 2025-07-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_client_options_alter_clientuser_options_and_more'),
        ('portal', '0015_alter_costcentercode_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='entities.client'),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='entities.supplier'),
        ),
    ]
