# Generated by Django 5.2.5 on 2025-09-03 07:46

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_addressbook_client_alter_addressbook_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivenotification',
            name='operations_archive',
            field=core.fields.MSSQLJSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='client_receivers',
            field=core.fields.MSSQLJSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='operations_receivers',
            field=core.fields.MSSQLJSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='supplier_receivers',
            field=core.fields.MSSQLJSONField(blank=True, default=list, null=True),
        ),
    ]
