# Generated by Django 5.2.5 on 2025-09-03 07:47

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_archivenotification_operations_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivenotification',
            name='client_archive',
            field=core.fields.MSSQLJSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='archivenotification',
            name='supplier_archive',
            field=core.fields.MSSQLJSONField(blank=True, default=list, null=True),
        ),
    ]
