# Generated by Django 5.2.5 on 2025-10-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_archivenotification_client_archive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='description',
            new_name='message',
        ),
    ]
