# Generated by Django 5.2.5 on 2025-10-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_rename_description_notification_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='title',
            new_name='header',
        ),
    ]
