# Generated by Django 5.2.5 on 2025-10-17 07:56

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_rename_title_notification_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='users',
            field=core.fields.MSSQLJSONField(blank=True, default=list, null=True),
        ),
    ]
