# Generated by Django 5.2.5 on 2025-10-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_notification_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivenotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
