# Generated by Django 5.2.5 on 2025-10-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_archivenotification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivenotification',
            name='is_read',
        ),
    ]
