# Generated by Django 5.2.5 on 2025-10-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_archivenotification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivenotification',
            name='notif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_notification', to='portal.notification'),
        ),
    ]
