# Generated by Django 5.2.5 on 2025-10-21 11:55

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_alter_usernotification_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='client_receivers',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='operations_receivers',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='supplier_receivers',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='client_archive',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='operations_archive',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='supplier_archive',
        ),
        migrations.AddField(
            model_name='notification',
            name='hyperlink_value',
            field=core.fields.MSSQLJSONField(blank=True, default=dict, null=True),
        ),
    ]
