# Generated by Django 5.2.5 on 2025-11-10 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_remove_notification_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentercode',
            name='sloc',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
