# Generated by Django 5.2.5 on 2025-11-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_costcentercode_sloc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costcentercode',
            unique_together={('plant_id', 'center_code', 'sloc')},
        ),
    ]
