# Generated by Django 5.2.5 on 2025-11-10 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0019_storerkey_cc_code'),
        ('portal', '0030_alter_costcentercode_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='storerkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='entities.storerkey'),
        ),
    ]
