# Generated by Django 5.2.5 on 2025-11-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_addressbook_storerkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='address_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Supplier', 'Supplier'), ('Storerkey', 'Storerkey')], max_length=10),
        ),
    ]
