# Generated by Django 5.2.5 on 2025-12-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_alter_addressbook_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='po/notifications/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Consignment', 'Consignment'), ('Purchase Order', 'Purchase Order'), ('Console', 'Console'), ('Expediting', 'Expediting'), ('PO File Upload', 'PO File Upload')], default='Consignment', max_length=20),
        ),
    ]
