# Generated by Django 5.2.5 on 2025-12-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0090_comprehensivereport_consignment_ids'),
        ('portal', '0033_notification_attachment_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='attachment',
        ),
        migrations.AddField(
            model_name='notification',
            name='po_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.purchaseorderupload'),
        ),
    ]
