# Generated by Django 5.2.5 on 2025-12-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_remove_notification_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attachment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
