# Generated by Django 5.2.5 on 2025-12-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_notification_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='attachment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
