# Generated by Django 5.2.5 on 2025-12-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_alter_notification_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Consignment', 'Consignment'), ('Purchase Order', 'Purchase Order'), ('Console', 'Console'), ('Expediting', 'Expediting'), ('PO File Upload', 'PO File Upload'), ('Comprehensive Report', 'Comprehensive Report')], default='Consignment', max_length=20),
        ),
    ]
