# Generated by Django 5.2.5 on 2025-12-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0025_client_client_code_idx_client_client_name_idx_and_more'),
        ('portal', '0037_alter_notification_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['client'], name='addr_client_idx'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['supplier'], name='addr_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['storerkey'], name='addr_storerkey_idx'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['address_type'], name='addr_type_idx'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['client', 'address_type'], name='addr_client_type_idx'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['supplier', 'address_type'], name='addr_supplier_type_idx'),
        ),
    ]
