# Generated by Django 5.1.6 on 2025-06-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='console',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consoleaudittrail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consoleaudittrailfield',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consoleffdocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='xml',
            options={},
        ),
    ]
