# Generated by Django 5.0.14 on 2025-06-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_console_console_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bol',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='console',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consoleaudittrail',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consoleaudittrailfield',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consoleffdocument',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='xml',
            options={'ordering': ('id',)},
        ),
    ]
