# Generated by Django 5.0.14 on 2025-06-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_bol_options_alter_console_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='console',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consoleaudittrail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consoleaudittrailfield',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consoleffdocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='xml',
            options={},
        ),
    ]
