# Generated by Django 5.0.14 on 2025-07-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_alter_bol_options_alter_console_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='console_status',
            field=models.CharField(choices=[('In Transit', 'In Transit'), ('At Customs', 'At Customs'), ('Delivered', 'Delivered'), ('New', 'New'), ('Freight Forwarder Assigned', 'Freight Forwarder Assigned'), ('Pickup Rejected', 'Pickup Rejected'), ('Partially Received', 'Partially Received')], default='New', max_length=100),
        ),
    ]
