# Generated by Django 5.0.14 on 2025-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_alter_console_console_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='console_status',
            field=models.CharField(choices=[('In Transit', 'In Transit'), ('At Customs', 'At Customs'), ('Delivered', 'Delivered'), ('New', 'New'), ('Freight Forwarder Assigned', 'Freight Forwarder Assigned'), ('Pickup Rejected', 'Pickup Rejected'), ('Partially Received', 'Partially Received'), ('Partially Delivered', 'Partially Delivered'), ('Received At Destination', 'Received At Destination'), ('Cancelled', 'Cancelled')], default='New', max_length=100),
        ),
    ]
