# Generated by Django 5.0.14 on 2025-07-22 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_alter_costcentercode_unique_together'),
        ('workflows', '0008_alter_console_console_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consoles', to='portal.glaccount'),
        ),
    ]
