# Generated by Django 5.0.14 on 2025-07-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_alter_console_gl_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsoleFFDocument',
        ),
    ]
