# Generated by Django 5.2.5 on 2025-09-19 07:48

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_alter_bol_gl_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bol',
            name='cc_code',
        ),
        migrations.RemoveField(
            model_name='bol',
            name='console',
        ),
        migrations.RemoveField(
            model_name='bol',
            name='freight_forwarder',
        ),
        migrations.RemoveField(
            model_name='bol',
            name='gl_account',
        ),
        migrations.RemoveField(
            model_name='bol',
            name='ship_from',
        ),
        migrations.RemoveField(
            model_name='bol',
            name='ship_to',
        ),
        migrations.RemoveField(
            model_name='bol',
            name='supplier',
        ),
        migrations.AddField(
            model_name='bol',
            name='cc_codes',
            field=core.fields.MSSQLJSONField(blank=True, default=list, null=True),
        ),
    ]
