# Generated by Django 5.2.5 on 2025-09-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0012_remove_bol_cc_code_remove_bol_console_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='gl_account',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
