# Generated by Django 5.2.5 on 2025-09-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0064_remove_consignment_bol'),
        ('workflows', '0013_bol_gl_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BOL',
        ),
    ]
