# Generated by Django 5.2.5 on 2025-12-10 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_addressbook_addr_client_idx_and_more'),
        ('workflows', '0014_delete_bol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='console',
            index=models.Index(fields=['console_id'], name='console_id_idx'),
        ),
        migrations.AddIndex(
            model_name='console',
            index=models.Index(fields=['console_status'], name='console_status_idx'),
        ),
        migrations.AddIndex(
            model_name='console',
            index=models.Index(fields=['freight_forwarder'], name='console_ff_idx'),
        ),
        migrations.AddIndex(
            model_name='console',
            index=models.Index(fields=['gl_account'], name='console_gl_idx'),
        ),
        migrations.AddIndex(
            model_name='console',
            index=models.Index(fields=['created_at'], name='console_created_idx'),
        ),
        migrations.AddIndex(
            model_name='console',
            index=models.Index(fields=['console_status', 'created_at'], name='console_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='xml',
            index=models.Index(fields=['xml_id'], name='xml_id_idx'),
        ),
        migrations.AddIndex(
            model_name='xml',
            index=models.Index(fields=['generated_by'], name='xml_generated_by_idx'),
        ),
        migrations.AddIndex(
            model_name='xml',
            index=models.Index(fields=['created_at'], name='xml_created_idx'),
        ),
    ]
