# Generated by Django 5.1.6 on 2025-06-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhocpurchaseorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='adhocpurchaseorderline',
            options={},
        ),
    ]
