# Generated by Django 5.0.14 on 2025-06-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0002_alter_adhocpurchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhocpurchaseorder',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='adhocpurchaseorderline',
            options={'ordering': ('id',)},
        ),
    ]
