# Generated by Django 5.0.14 on 2025-06-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0003_alter_adhocpurchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhocpurchaseorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='adhocpurchaseorderline',
            options={},
        ),
    ]
