# Generated by Django 5.1.6 on 2025-06-12 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consignmentaudittrail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consignmentaudittrailfield',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consignmentdocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consignmentdocumentattachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consignmentdocumentattachmentstaging',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consignmentdocumentstaging',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consignmentffdocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consignmentpackaging',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consignmentpackagingstaging',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consignmentpolinestaging',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consignmentstaging',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packagingallocation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packagingallocationstaging',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderdetail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderlinedetail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='temporarypurchaseorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usergridpreferences',
            options={},
        ),
        migrations.CreateModel(
            name='PurchaseOrderUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('In Progress', 'In Progress')], default='In Progress', max_length=15)),
                ('uploaded_file', models.FileField(upload_to='po/upload/')),
                ('error_file', models.FileField(blank=True, null=True, upload_to='po/upload/errors/')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
