# Generated by Django 5.1.6 on 2025-06-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_consignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentaudittrailfield',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consignmentaudittrailfield',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consignmentaudittrailfield',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
