# Generated by Django 5.0.14 on 2025-06-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_consignmentaudittrailfield_attachments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={},
        ),
    ]
