# Generated by Django 5.0.14 on 2025-06-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_purchaseorderline_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consignment',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consignmentaudittrail',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consignmentaudittrailfield',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consignmentdocument',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consignmentdocumentattachment',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consignmentdocumentattachmentstaging',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consignmentdocumentstaging',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consignmentffdocument',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consignmentpackaging',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consignmentpackagingstaging',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consignmentpolinestaging',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='consignmentstaging',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='packagingallocation',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='packagingallocationstaging',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderdetail',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderlinedetail',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderupload',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='temporarypurchaseorder',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='usergridpreferences',
            options={'ordering': ('id',)},
        ),
    ]
