# Generated by Django 5.0.14 on 2025-06-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_consignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={'ordering': ('customer_reference_number',)},
        ),
    ]
