# Generated by Django 5.0.14 on 2025-06-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_purchaseorderline_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={},
        ),
    ]
