# Generated by Django 5.0.14 on 2025-07-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_consignmentpackaging_status_and_more'),
        ('operations', '0010_consignmentpackagingstaging_weight_and_more'),
    ]

    operations = [
    ]
