# Generated by Django 5.0.14 on 2025-07-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_merge_20250701_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentpackagingstaging',
            name='received_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consignmentpackagingstaging',
            name='time_zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
