# Generated by Django 5.0.14 on 2025-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_consignmentpackagingstaging_received_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentpackagingstaging',
            name='received_date_time',
        ),
        migrations.RemoveField(
            model_name='consignmentpackagingstaging',
            name='time_zone',
        ),
        migrations.AddField(
            model_name='consignmentpackaging',
            name='received_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consignmentpackaging',
            name='time_zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
