# Generated by Django 5.0.14 on 2025-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_remove_consignmentpackagingstaging_received_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='consignment_status',
            field=models.CharField(choices=[('Pending For Approval', 'Pending For Approval'), ('Pickup Completed', 'Pickup Completed'), ('Pending Bid', 'Pending Bid'), ('At Customs', 'At Customs'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Received At Destination', 'Received At Destination'), ('Pending Console Assignment', 'Pending Console Assignment'), ('Freight Forwarder Assigned', 'Freight Forwarder Assigned'), ('Console Assigned', 'Console Assigned'), ('Out For Delivery', 'Out For Delivery'), ('Partially Received', 'Partially Received')], default='Pending For Approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
