# Generated by Django 5.0.14 on 2025-07-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_alter_consignment_consignment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentpackaging',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consignmentpackaging',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Pound', 'Pound'), ('Ounce', 'Ounce')], max_length=20, null=True),
        ),
    ]
