# Generated by Django 5.0.14 on 2025-07-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_consignmentpackaging_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='cancellation_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
