# Generated by Django 5.0.14 on 2025-07-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_consignment_cancellation_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentdocument',
            name='document_type',
            field=models.CharField(choices=[('COMMERCIAL INVOICE', 'COMMERCIAL INVOICE'), ('DANGEROUS GOOD', 'DANGEROUS GOOD'), ('Bill of Materials', 'Bill of Materials'), ('Packing List', 'Packing List'), ('MSDS', 'MSDS'), ('SSDS', 'SSDS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='consignmentdocumentstaging',
            name='document_type',
            field=models.CharField(choices=[('COMMERCIAL INVOICE', 'COMMERCIAL INVOICE'), ('DANGEROUS GOOD', 'DANGEROUS GOOD'), ('Bill of Materials', 'Bill of Materials'), ('Packing List', 'Packing List'), ('MSDS', 'MSDS'), ('SSDS', 'SSDS')], max_length=50),
        ),
    ]
