# Generated by Django 5.0.14 on 2025-07-17 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_alter_consignmentdocument_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWBFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='consignments/awb/')),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment', to='operations.consignment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
