# Generated by Django 5.0.14 on 2025-07-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_awbfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AWBFiles',
            new_name='AWBFile',
        ),
    ]
