# Generated by Django 5.0.14 on 2025-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_rename_awbfiles_awbfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='gl_code',
            field=models.CharField(choices=[('56000100', '56000100'), ('56010000', '56010000')], default='56000100', max_length=50),
        ),
    ]
