# Generated by Django 5.0.14 on 2025-07-23 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_consignment_gl_code'),
        ('workflows', '0009_alter_console_gl_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='console',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments', to='workflows.console'),
        ),
    ]
