# Generated by Django 5.0.14 on 2025-07-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_client_options_alter_clientuser_options_and_more'),
        ('operations', '0022_alter_consignment_console'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['reference_number'], name='operations__referen_7f5cad_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['customer_reference_number'], name='operations__custome_1e1247_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['open_quantity'], name='operations__open_qu_627965_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='operations__status_1ac0b8_idx'),
        ),
    ]
