# Generated by Django 5.0.14 on 2025-07-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_consignment_last_bol_generated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignment',
            old_name='last_bol_generated_at',
            new_name='last_bol_gen_at',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='last_bol_generated_by',
            new_name='last_bol_gen_by',
        ),
    ]
