# Generated by Django 5.0.14 on 2025-07-31 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_rename_last_bol_generated_at_consignment_last_bol_gen_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awbfile',
            name='consignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_awb', to='operations.consignment'),
        ),
    ]
