# Generated by Django 5.2.5 on 2025-08-18 06:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_dangerousgood'),
        ('operations', '0026_alter_awbfile_consignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='batch',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='inco_terms',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='lot',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='origin_country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='alternate_unit',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='customer_reference_number',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='fulfilled_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='hs_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='open_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='processed_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='reference_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='sku',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='source_location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Open', 'Open'), ('Partially Fulfilled', 'Partially Fulfilled')], default='Open', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='stock_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderlinedetail',
            name='retail_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=128, unique=True)),
                ('is_chemical', models.BooleanField(default=False)),
                ('is_dangerous_good', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(max_length=128)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('hs_code', models.CharField(blank=True, max_length=128, null=True)),
                ('stock_number', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('alternate_unit', models.CharField(blank=True, max_length=128, null=True)),
                ('alternate_sku', models.CharField(blank=True, max_length=128, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=50, null=True)),
                ('to_expire_days', models.PositiveSmallIntegerField(default=0)),
                ('to_delivery_days', models.PositiveSmallIntegerField(default=0)),
                ('to_best_by_days', models.PositiveSmallIntegerField(default=0)),
                ('is_kit', models.BooleanField(default=False)),
                ('is_stackable', models.BooleanField(default=False)),
                ('inspection_required', models.BooleanField(default=False)),
                ('shelf_life', models.PositiveSmallIntegerField(default=0)),
                ('shelf_life_indicator', models.CharField(blank=True, max_length=256, null=True)),
                ('sku_class', models.CharField(blank=True, max_length=256, null=True)),
                ('retail_sku', models.CharField(blank=True, max_length=256, null=True)),
                ('hazmat_codes_keys', models.CharField(blank=True, max_length=256, null=True)),
                ('susr1', models.CharField(blank=True, max_length=256, null=True)),
                ('susr2', models.CharField(blank=True, max_length=256, null=True)),
                ('susr3', models.CharField(blank=True, max_length=256, null=True)),
                ('susr4', models.CharField(blank=True, max_length=256, null=True)),
                ('susr5', models.CharField(blank=True, max_length=256, null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_master', to='entities.hub')),
                ('storerkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_master', to='entities.storerkey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
