# Generated by Django 5.2.5 on 2025-08-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_purchaseorderline_batch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialMaster',
        ),
    ]
