# Generated by Django 5.2.5 on 2025-08-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_rename_reminder_name_storerkeyreminder_name_and_more'),
        ('operations', '0028_delete_materialmaster'),
    ]

    operations = [
        # migrations.AddConstraint(
        #     model_name='purchaseorder',
        #     constraint=models.CheckConstraint(condition=models.Q(('open_quantity__gte', 0)), name='check_po_open_non_negative'),
        # ),
        # migrations.AddConstraint(
        #     model_name='purchaseorderline',
        #     constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='check_pol_quantity_non_negative'),
        # ),
        # migrations.AddConstraint(
        #     model_name='purchaseorderline',
        #     # constraint=models.CheckConstraint(condition=models.Q(('fulfilled_quantity__gte', 0)), name='check_pol_fulfilled_non_negative'),
        # ),
        # migrations.AddConstraint(
        #     model_name='purchaseorderline',
        #     constraint=models.CheckConstraint(condition=models.Q(('processed_quantity__gte', 0)), name='check_pol_processed_non_negative'),
        # ),
        # migrations.AddConstraint(
        #     model_name='purchaseorderline',
        #     constraint=models.CheckConstraint(condition=models.Q(('open_quantity__gte', 0)), name='check_pol_open_non_negative'),
        # ),
    ]
