# Generated by Django 5.2.5 on 2025-08-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_purchaseorder_check_po_open_non_negative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='consignment',
            name='purchase_order',
            field=models.ManyToManyField(blank=True, related_name='consignments', to='operations.purchaseorder'),
        ),
    ]
