# Generated by Django 5.2.5 on 2025-09-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_remove_consignment_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='purchase_order',
            field=models.ManyToManyField(blank=True, related_name='consignments', through='operations.ConsignmentPurchaseOrder', to='operations.purchaseorder'),
        ),
    ]
