# Generated by Django 5.2.5 on 2025-09-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_rename_reminder_name_storerkeyreminder_name_and_more'),
        ('operations', '0032_consignment_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='entities.client'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='entities.supplier'),
        ),
    ]
