# Generated by Django 5.2.5 on 2025-09-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_alter_consignment_client_alter_consignment_supplier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consignmentpurchaseorder',
            unique_together={('consignment', 'purchase_order')},
        ),
    ]
