# Generated by Django 5.2.5 on 2025-09-03 07:46

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0034_alter_consignmentpurchaseorder_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrailfield',
            name='attachments',
            field=core.fields.MSSQLJSONField(default=list),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='packages',
            field=core.fields.MSSQLJSONField(default=list),
        ),
        migrations.AlterField(
            model_name='consignmentaudittrailfield',
            name='attachments',
            field=core.fields.MSSQLJSONField(default=list),
        ),
        migrations.AlterField(
            model_name='consignmentpolinestaging',
            name='packages',
            field=core.fields.MSSQLJSONField(default=list),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='buyer_details',
            field=core.fields.MSSQLJSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='temporarypurchaseorder',
            name='data',
            field=core.fields.MSSQLJSONField(default=list),
        ),
        migrations.AlterField(
            model_name='usergridpreferences',
            name='order_list',
            field=core.fields.MSSQLJSONField(default=list),
        ),
    ]
