# Generated by Django 5.2.5 on 2025-09-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0035_alter_audittrailfield_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='eccn',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
