# Generated by Django 5.2.5 on 2025-09-04 10:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_remove_dangerousgoodclass_code'),
        ('operations', '0036_purchaseorderline_eccn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentdocumentattachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='eccn',
        ),
        migrations.AddField(
            model_name='consignmentdocument',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='consignments/documents/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConsignmentPOLineBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='operations.consignment')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='operations.purchaseorderline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsignmentPOLineCompliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hs_code', models.CharField(blank=True, max_length=100, null=True)),
                ('eccn', models.BooleanField(default=False)),
                ('dg_note', models.TextField(blank=True, null=True)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='operations.consignment')),
                ('dg_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='entities.dangerousgoodcategory')),
                ('dg_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='entities.dangerousgoodclass')),
                ('dg_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_document', to='operations.consignmentdocument')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='operations.purchaseorderline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
