# Generated by Django 5.2.5 on 2025-09-04 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0037_remove_consignmentdocumentattachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentdocumentattachment',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='consignments/documents/'),
            preserve_default=False,
        ),
    ]
