# Generated by Django 5.2.5 on 2025-09-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0038_consignmentdocumentattachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentpolinecompliance',
            name='dg_document',
        ),
        migrations.AddField(
            model_name='consignmentdocument',
            name='compliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='operations.consignmentpolinecompliance'),
        ),
    ]
