# Generated by Django 5.2.5 on 2025-09-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0039_remove_consignmentpolinecompliance_dg_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpolinecompliance',
            name='eccn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentpolinecompliance',
            name='hs_code',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
