# Generated by Django 5.2.5 on 2025-09-08 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0040_alter_consignmentpolinecompliance_eccn_and_more'),
        ('portal', '0018_alter_archivenotification_client_archive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagingallocation',
            name='adhoc_line',
        ),
        migrations.RemoveField(
            model_name='packagingallocation',
            name='eccn',
        ),
        migrations.RemoveField(
            model_name='packagingallocation',
            name='hs_code',
        ),
        migrations.RemoveField(
            model_name='packagingallocation',
            name='manufacturing_country',
        ),
        migrations.AddField(
            model_name='consignmentpackaging',
            name='allocated_lines',
            field=models.ManyToManyField(blank=True, related_name='packages', through='operations.PackagingAllocation', to='operations.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='consignmentpackaging',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consignmentpackaging',
            name='packaging_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignment_packagings', to='portal.packagingtype'),
        ),
    ]
