# Generated by Django 5.2.5 on 2025-09-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0041_remove_packagingallocation_adhoc_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentpackaging',
            name='draft_package_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
