# Generated by Django 5.2.5 on 2025-09-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0042_consignmentpackaging_draft_package_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consignmentpackaging',
            unique_together={('draft_package_id', 'consignment')},
        ),
    ]
