# Generated by Django 5.2.5 on 2025-09-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0043_alter_consignmentpackaging_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='step',
            field=models.CharField(choices=[('Step 1', 'Step 1'), ('Step 2', 'Step 2'), ('Step 3', 'Step 3'), ('Step 4', 'Step 4'), ('Step 5', 'Step 5')], default='Step 1', max_length=10),
        ),
    ]
