# Generated by Django 5.2.5 on 2025-09-10 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0044_alter_consignment_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='additional_instructions',
            field=models.TextField(default=datetime.datetime(2025, 9, 10, 9, 34, 57, 804328, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
