# Generated by Django 5.2.5 on 2025-09-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0045_consignment_additional_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpolinebatch',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
