# Generated by Django 5.2.5 on 2025-09-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_remove_dangerousgoodclass_code'),
        ('operations', '0046_alter_consignmentpolinebatch_expiry_date'),
    ]

    operations = [
        # migrations.AddConstraint(
        #     model_name='purchaseorder',
        #     constraint=models.CheckConstraint(condition=models.Q(open_quantity__gte=0), name='check_po_open_non_negative'),
        # ),
        # migrations.AddConstraint(
        #     model_name='purchaseorderline',
        #     constraint=models.CheckConstraint(condition=models.Q(quantity__gte= 0), name='check_pol_quantity_non_negative'),
        # ),
        # migrations.AddConstraint(
        #     model_name='purchaseorderline',
        #     constraint=models.CheckConstraint(condition=models.Q(fulfilled_quantity__gte=0), name='check_pol_fulfilled_non_negative'),
        # ),
        # migrations.AddConstraint(
        #     model_name='purchaseorderline',
        #     constraint=models.CheckConstraint(condition=models.Q(processed_quantity__gte=0), name='check_pol_processed_non_negative'),
        # ),
        # migrations.AddConstraint(
        #     model_name='purchaseorderline',
        #     constraint=models.CheckConstraint(condition=models.Q(open_quantity__gte=0), name='check_pol_open_non_negative'),
        # ),
    ]
