# Generated by Django 5.2.5 on 2025-09-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0047_purchaseorder_check_po_open_non_negative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentdocument',
            name='file',
        ),
    ]
