# Generated by Django 5.2.5 on 2025-09-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0004_alter_adhocpurchaseorder_options_and_more'),
        ('entities', '0016_remove_dangerousgoodclass_code'),
        ('operations', '0048_remove_consignmentdocument_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentdocument',
            name='compliance',
        ),
        migrations.AlterField(
            model_name='consignmentpolinecompliance',
            name='dg_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliances', to='entities.dangerousgoodcategory'),
        ),
        migrations.AlterField(
            model_name='consignmentpolinecompliance',
            name='dg_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliances', to='entities.dangerousgoodclass'),
        ),
        migrations.AlterField(
            model_name='consignmentpolinecompliance',
            name='eccn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentpolinecompliance',
            name='hs_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='consignmentpolinecompliance',
            unique_together={('consignment', 'purchase_order_line')},
        ),
        migrations.AddIndex(
            model_name='consignmentdocument',
            index=models.Index(fields=['consignment', 'document_type'], name='operations__consign_00f487_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpolinecompliance',
            index=models.Index(fields=['consignment', 'purchase_order_line'], name='operations__consign_7e0184_idx'),
        ),
    ]
