# Generated by Django 5.2.5 on 2025-09-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0049_remove_consignmentdocument_compliance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpurchaseorder',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='operations.purchaseorder'),
        ),
    ]
