# Generated by Django 5.2.5 on 2025-09-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0050_alter_consignmentpurchaseorder_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
