# Generated by Django 5.2.5 on 2025-09-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0051_consignment_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='is_draft',
        ),
    ]
