# Generated by Django 5.2.5 on 2025-09-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0052_remove_consignment_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentpolinecompliance',
            name='is_chemical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consignmentpolinecompliance',
            name='is_dangerous_good',
            field=models.BooleanField(default=False),
        ),
    ]
