# Generated by Django 5.2.5 on 2025-09-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0053_consignmentpolinecompliance_is_chemical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentpolinecompliance',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
