# Generated by Django 5.2.5 on 2025-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0054_consignmentpolinecompliance_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentpackaging',
            name='order_type',
            field=models.CharField(blank=True, choices=[('BTS', 'BTS'), ('BTO', 'BTO')], default=None, max_length=20, null=True),
        ),
    ]
