# Generated by Django 5.2.5 on 2025-09-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0055_consignmentpackaging_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpackaging',
            name='package_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
