# Generated by Django 5.2.5 on 2025-09-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0056_alter_consignmentpackaging_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpackaging',
            name='package_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
