# Generated by Django 5.2.5 on 2025-09-15 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0057_alter_consignmentpackaging_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentdocument',
            name='compliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.consignmentpolinecompliance'),
        ),
    ]
