# Generated by Django 5.2.5 on 2025-09-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0058_consignmentdocument_compliance'),
        ('portal', '0018_alter_archivenotification_client_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpackaging',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='consignmentpackaging',
            name='package_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='consignmentpackaging',
            name='status',
            field=models.CharField(choices=[('Not Received', 'Not Received'), ('Received', 'Received')], db_index=True, default='Not Received', max_length=20),
        ),
        migrations.AddIndex(
            model_name='consignmentpackaging',
            index=models.Index(fields=['consignment'], name='operations__consign_ca638c_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpackaging',
            index=models.Index(fields=['packaging_type'], name='operations__packagi_a8d559_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpackaging',
            index=models.Index(fields=['status'], name='operations__status_d5603b_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpackaging',
            index=models.Index(fields=['package_id'], name='operations__package_dad714_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpackaging',
            index=models.Index(fields=['is_draft'], name='operations__is_draf_8d584b_idx'),
        ),
    ]
