# Generated by Django 5.2.5 on 2025-09-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0059_alter_consignmentpackaging_is_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpackaging',
            name='status',
            field=models.CharField(choices=[('Not Received', 'Not Received'), ('Received', 'Received'), ('Draft', 'Draft'), ('Purchase Order Lines', 'Purchase Order Lines')], db_index=True, default='Not Received', max_length=20),
        ),
        migrations.AddIndex(
            model_name='packagingallocation',
            index=models.Index(fields=['consignment_packaging'], name='operations__consign_ba9768_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingallocation',
            index=models.Index(fields=['purchase_order_line'], name='operations__purchas_816c8c_idx'),
        ),
    ]
