# Generated by Django 5.2.5 on 2025-09-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0060_alter_consignmentpackaging_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consignmentpackaging',
            name='operations__is_draf_8d584b_idx',
        ),
        migrations.RemoveField(
            model_name='consignmentpackaging',
            name='is_draft',
        ),
    ]
