# Generated by Django 5.2.5 on 2025-09-17 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0061_remove_consignmentpackaging_operations__is_draf_8d584b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpolinebatch',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consignmentpolinebatch',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='consignmentpolinebatch',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
