# Generated by Django 5.2.5 on 2025-09-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0062_alter_consignmentpolinebatch_expiry_date_and_more'),
        ('workflows', '0012_remove_bol_cc_code_remove_bol_console_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='bol',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment', to='workflows.bol'),
        ),
    ]
