# Generated by Django 5.2.5 on 2025-09-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0063_alter_consignment_bol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='bol',
        ),
    ]
