# Generated by Django 5.2.5 on 2025-09-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0064_remove_consignment_bol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentdocument',
            name='consignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.consignment'),
        ),
        migrations.AlterField(
            model_name='consignmentdocument',
            name='document_type',
            field=models.CharField(choices=[('COMMERCIAL INVOICE', 'COMMERCIAL INVOICE'), ('DANGEROUS GOOD', 'DANGEROUS GOOD'), ('Bill of Materials', 'Bill of Materials'), ('Packing List', 'Packing List'), ('MSDS', 'MSDS'), ('SSDS', 'SSDS'), ('Comprehensive Report', 'Comprehensive Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='consignmentdocumentstaging',
            name='document_type',
            field=models.CharField(choices=[('COMMERCIAL INVOICE', 'COMMERCIAL INVOICE'), ('DANGEROUS GOOD', 'DANGEROUS GOOD'), ('Bill of Materials', 'Bill of Materials'), ('Packing List', 'Packing List'), ('MSDS', 'MSDS'), ('SSDS', 'SSDS'), ('Comprehensive Report', 'Comprehensive Report')], max_length=50),
        ),
    ]
