# Generated by Django 5.2.5 on 2025-09-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0065_alter_consignmentdocument_consignment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignmentpolinecompliance',
            old_name='is_chemical',
            new_name='compliance_chemical',
        ),
        migrations.RenameField(
            model_name='consignmentpolinecompliance',
            old_name='is_dangerous_good',
            new_name='compliance_dg',
        ),
    ]
