# Generated by Django 5.2.5 on 2025-09-24 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0066_rename_is_chemical_consignmentpolinecompliance_compliance_chemical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentPOLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.consignment')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='operations.purchaseorderline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consignment',
            name='purchase_order_lines',
            field=models.ManyToManyField(blank=True, related_name='consignments', through='operations.ConsignmentPOLine', to='operations.purchaseorderline'),
        ),
    ]
