# Generated by Django 5.2.5 on 2025-09-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0067_consignmentpoline_consignment_purchase_order_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentpoline',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='consignmentpoline',
            name='purchase_order_lines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignments_po_lines', to='operations.purchaseorderline'),
        ),
    ]
