# Generated by Django 5.2.5 on 2025-09-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0068_remove_consignmentpoline_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpoline',
            name='purchase_order_lines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments_po_lines', to='operations.purchaseorderline'),
        ),
    ]
