# Generated by Django 5.2.5 on 2025-09-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0069_alter_consignmentpoline_purchase_order_lines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignmentpoline',
            old_name='purchase_order_lines',
            new_name='purchase_order_line',
        ),
    ]
