# Generated by Django 5.2.5 on 2025-09-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0071_consignmentpoline_compliance_chemical_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentpoline',
            name='compliance_chemical',
        ),
        migrations.RemoveField(
            model_name='consignmentpoline',
            name='compliance_dg',
        ),
        migrations.RemoveField(
            model_name='consignmentpoline',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='consignmentpoline',
            name='dg_category',
        ),
        migrations.RemoveField(
            model_name='consignmentpoline',
            name='dg_class',
        ),
        migrations.RemoveField(
            model_name='consignmentpoline',
            name='dg_note',
        ),
        migrations.RemoveField(
            model_name='consignmentpoline',
            name='eccn',
        ),
        migrations.RemoveField(
            model_name='consignmentpoline',
            name='hs_code',
        ),
        migrations.AddField(
            model_name='consignmentpoline',
            name='compliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments_po_line', to='operations.consignmentpolinecompliance'),
        ),
        migrations.AlterField(
            model_name='consignmentpoline',
            name='consignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_po_line', to='operations.consignment'),
        ),
        migrations.AlterField(
            model_name='consignmentpoline',
            name='purchase_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments_po_line', to='operations.purchaseorderline'),
        ),
    ]
