# Generated by Django 5.2.5 on 2025-09-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_remove_dangerousgoodclass_code'),
        ('operations', '0072_remove_consignmentpoline_compliance_chemical_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentpoline',
            name='compliance',
        ),
        migrations.AddField(
            model_name='consignmentpoline',
            name='compliance_chemical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consignmentpoline',
            name='compliance_dg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consignmentpoline',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignmentpoline',
            name='dg_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.dangerousgoodcategory'),
        ),
        migrations.AddField(
            model_name='consignmentpoline',
            name='dg_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.dangerousgoodclass'),
        ),
        migrations.AddField(
            model_name='consignmentpoline',
            name='dg_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consignmentpoline',
            name='eccn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consignmentpoline',
            name='hs_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentpoline',
            name='purchase_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments_po_lines', to='operations.purchaseorderline'),
        ),
    ]
