# Generated by Django 5.2.5 on 2025-09-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0073_remove_consignmentpoline_compliance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consignmentpolinecompliance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='consignmentpolinecompliance',
            name='consignment',
        ),
        migrations.RemoveField(
            model_name='consignmentpolinecompliance',
            name='dg_category',
        ),
        migrations.RemoveField(
            model_name='consignmentpolinecompliance',
            name='dg_class',
        ),
        migrations.RemoveField(
            model_name='consignmentpolinecompliance',
            name='purchase_order_line',
        ),
        migrations.RemoveField(
            model_name='consignmentdocument',
            name='compliance',
        ),
        migrations.AlterUniqueTogether(
            name='consignmentpurchaseorder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='consignmentpurchaseorder',
            name='consignment',
        ),
        migrations.RemoveField(
            model_name='consignmentpurchaseorder',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='purchase_order',
        ),
        migrations.AlterUniqueTogether(
            name='consignmentpolinebatch',
            unique_together={('consignment', 'purchase_order_line')},
        ),
        migrations.AddIndex(
            model_name='consignmentpolinebatch',
            index=models.Index(fields=['consignment', 'purchase_order_line'], name='operations__consign_4074d0_idx'),
        ),
        migrations.DeleteModel(
            name='ConsignmentPOLineCompliance',
        ),
        migrations.DeleteModel(
            name='ConsignmentPurchaseOrder',
        ),
    ]
