# Generated by Django 5.2.5 on 2025-09-24 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0074_alter_consignmentpolinecompliance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentpoline',
            name='dg_note',
        ),
        migrations.CreateModel(
            name='DangerousGoodDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='consignments/documents/')),
                ('consignment_po_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_files', to='operations.consignmentpoline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
