# Generated by Django 5.2.5 on 2025-09-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0075_remove_consignmentpoline_dg_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentpoline',
            name='dg_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
