# Generated by Django 5.2.5 on 2025-09-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0076_consignmentpoline_dg_note'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consignmentpolinebatch',
            name='operations__consign_4074d0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='consignmentpolinebatch',
            unique_together=set(),
        ),
    ]
