# Generated by Django 5.2.5 on 2025-09-25 14:20

import core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0077_remove_consignmentpolinebatch_operations__consign_4074d0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('status', core.fields.MSSQLJSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
