# Generated by Django 5.2.5 on 2025-09-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0079_comprehensivereport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentpackaging',
            name='is_kit',
            field=models.BooleanField(default=False),
        ),
    ]
