# Generated by Django 5.2.5 on 2025-09-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0080_consignmentpackaging_is_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='additional_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
