# Generated by Django 5.2.5 on 2025-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0081_alter_consignment_additional_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderupload',
            name='file_format',
            field=models.CharField(choices=[('Standard Format', 'Standard Format'), ('SLB', 'SLB')], default='Standard Format', max_length=15),
        ),
    ]
