# Generated by Django 5.2.5 on 2025-10-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0082_purchaseorderupload_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderupload',
            name='file_format',
            field=models.CharField(choices=[('PO', 'PO'), ('SLB', 'SLB')], default='PO', max_length=15),
        ),
        migrations.AlterField(
            model_name='purchaseorderupload',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('In Progress', 'In Progress'), ('Failed', 'Failed')], default='In Progress', max_length=15),
        ),
    ]
