# Generated by Django 5.2.5 on 2025-10-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0083_alter_purchaseorderupload_file_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpolinebatch',
            name='number',
            field=models.CharField(max_length=25),
        ),
    ]
