# Generated by Django 5.2.5 on 2025-10-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0084_alter_consignmentpolinebatch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentdocument',
            name='document_type',
            field=models.CharField(choices=[('Commercial Invoice', 'Commercial Invoice'), ('Dangerous Good', 'Dangerous Good'), ('Bill of Materials', 'Bill of Materials'), ('Packing List', 'Packing List'), ('MSDS', 'MSDS'), ('SSDS', 'SSDS'), ('Comprehensive Report', 'Comprehensive Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='consignmentdocumentstaging',
            name='document_type',
            field=models.CharField(choices=[('Commercial Invoice', 'Commercial Invoice'), ('Dangerous Good', 'Dangerous Good'), ('Bill of Materials', 'Bill of Materials'), ('Packing List', 'Packing List'), ('MSDS', 'MSDS'), ('SSDS', 'SSDS'), ('Comprehensive Report', 'Comprehensive Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='consignmentpackaging',
            name='status',
            field=models.CharField(choices=[('Not Received', 'Not Received'), ('Received', 'Received'), ('Draft', 'Draft'), ('Purchase Order Lines', 'Purchase Order Lines'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], db_index=True, default='Not Received', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderupload',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('In Progress', 'In Progress'), ('Failed', 'Failed'), ('Queue', 'Queue')], default='In Progress', max_length=15),
        ),
    ]
