# Generated by Django 5.2.5 on 2025-11-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0085_alter_consignmentdocument_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentdocumentstaging',
            name='consignment',
        ),
        migrations.RemoveField(
            model_name='consignmentpackagingstaging',
            name='consignment',
        ),
        migrations.RemoveField(
            model_name='consignmentpackagingstaging',
            name='packaging_type',
        ),
        migrations.RemoveField(
            model_name='packagingallocationstaging',
            name='consignment_packaging',
        ),
        migrations.RemoveField(
            model_name='consignmentpolinestaging',
            name='consignment',
        ),
        migrations.RemoveField(
            model_name='consignmentpolinestaging',
            name='purchase_order_line',
        ),
        migrations.RemoveField(
            model_name='packagingallocationstaging',
            name='po_line',
        ),
        migrations.RemoveField(
            model_name='consignmentstaging',
            name='consignor_address',
        ),
        migrations.RemoveField(
            model_name='consignmentstaging',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='consignmentstaging',
            name='purchase_orders',
        ),
        migrations.RemoveField(
            model_name='consignmentstaging',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConsignmentDocumentAttachmentStaging',
        ),
        migrations.DeleteModel(
            name='ConsignmentDocumentStaging',
        ),
        migrations.DeleteModel(
            name='ConsignmentPackagingStaging',
        ),
        migrations.DeleteModel(
            name='ConsignmentPOLineStaging',
        ),
        migrations.DeleteModel(
            name='PackagingAllocationStaging',
        ),
        migrations.DeleteModel(
            name='ConsignmentStaging',
        ),
    ]
