# Generated by Django 5.2.5 on 2025-11-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0087_alter_consignment_consignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpackaging',
            name='order_type',
            field=models.CharField(blank=True, choices=[('BTS', 'BTS'), ('BTO', 'BTO'), ('Both', 'Both')], default=None, max_length=20, null=True),
        ),
    ]
