# Generated by Django 5.2.5 on 2025-11-14 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0088_alter_consignmentpackaging_order_type'),
        ('workflows', '0014_delete_bol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='console',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments', to='workflows.console'),
        ),
    ]
