# Generated by Django 5.2.5 on 2025-11-18 11:20

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0089_alter_consignment_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehensivereport',
            name='consignment_ids',
            field=core.fields.MSSQLJSONField(default=list),
        ),
    ]
