# Generated by Django 5.2.5 on 2025-12-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0090_comprehensivereport_consignment_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehensivereport',
            name='report_generation_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('In Progress', 'In Progress'), ('Failed', 'Failed'), ('Queue', 'Queue')], db_index=True, default='In Progress', max_length=20),
        ),
    ]
