# Generated by Django 5.2.5 on 2025-12-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0091_comprehensivereport_report_generation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprehensivereport',
            name='report_generation_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('In Progress', 'In Progress'), ('Failed', 'Failed'), ('Queue', 'Queue')], db_index=True, default='Queue', max_length=20),
        ),
    ]
