# Generated by Django 5.2.5 on 2025-12-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0092_alter_comprehensivereport_report_generation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_type',
            field=models.CharField(choices=[('BTS', 'BTS'), ('BTO', 'BTO'), ('Both', 'Both')], default='BTS', max_length=5),
        ),
    ]
