# Generated by Django 5.2.5 on 2025-12-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0024_remove_client_can_add_shipto_add_and_more'),
        ('operations', '0093_purchaseorder_po_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='operations__referen_7f5cad_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='po_crn_idx',
            old_name='operations__custome_1e1247_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='po_open_quantity_idx',
            old_name='operations__open_qu_627965_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='po_status_idx',
            old_name='operations__status_1ac0b8_idx',
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'storerkey'], name='po_supplier_storerkey_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_at', 'is_deleted'], name='po_created_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['purchase_order', 'customer_reference_number'], name='pol_po_crn_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['purchase_order', 'is_deleted'], name='pol_purchase_order_idx'),
        ),
    ]
