# Generated by Django 5.2.5 on 2025-12-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0094_remove_purchaseorder_operations__referen_7f5cad_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='po_type',
            new_name='order_type',
        ),
    ]
