# Generated by Django 5.2.5 on 2025-12-10 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0004_alter_adhocpurchaseorder_options_and_more'),
        ('entities', '0025_client_client_code_idx_client_client_name_idx_and_more'),
        ('operations', '0095_rename_po_type_purchaseorder_order_type'),
        ('portal', '0038_addressbook_addr_client_idx_and_more'),
        ('workflows', '0015_console_console_id_idx_console_console_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='po_open_quantity_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='po_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='po_supplier_storerkey_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorderline',
            name='pol_purchase_order_idx',
        ),
        migrations.RenameIndex(
            model_name='consignmentpackaging',
            new_name='pkg_consignment_idx',
            old_name='operations__consign_ca638c_idx',
        ),
        migrations.RenameIndex(
            model_name='consignmentpackaging',
            new_name='pkg_type_idx',
            old_name='operations__packagi_a8d559_idx',
        ),
        migrations.RenameIndex(
            model_name='consignmentpackaging',
            new_name='pkg_status_idx',
            old_name='operations__status_d5603b_idx',
        ),
        migrations.RenameIndex(
            model_name='consignmentpackaging',
            new_name='pkg_id_idx',
            old_name='operations__package_dad714_idx',
        ),
        migrations.RenameIndex(
            model_name='packagingallocation',
            new_name='alloc_pkg_idx',
            old_name='operations__consign_ba9768_idx',
        ),
        migrations.RenameIndex(
            model_name='packagingallocation',
            new_name='alloc_po_line_idx',
            old_name='operations__purchas_816c8c_idx',
        ),
        migrations.AddIndex(
            model_name='comprehensivereport',
            index=models.Index(fields=['user'], name='report_user_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensivereport',
            index=models.Index(fields=['report_generation_status'], name='report_gen_status_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensivereport',
            index=models.Index(fields=['from_date', 'to_date'], name='report_date_range_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensivereport',
            index=models.Index(fields=['created_at'], name='report_created_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensivereport',
            index=models.Index(fields=['user', 'report_generation_status'], name='report_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['consignment_id'], name='consignment_id_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['supplier'], name='consignment_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['client'], name='consignment_client_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['console'], name='consignment_console_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['consignment_status'], name='consignment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['consignment_status', 'is_deleted'], name='consignment_status_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['supplier', 'consignment_status', 'is_deleted'], name='cons_supplier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['console', 'consignment_status'], name='consignment_console_status_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['created_by'], name='consignment_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['created_at', 'is_deleted'], name='cons_created_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentdocument',
            index=models.Index(fields=['consignment'], name='doc_consignment_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentdocument',
            index=models.Index(fields=['document_type'], name='doc_type_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpackaging',
            index=models.Index(fields=['draft_package_id'], name='pkg_draft_id_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpackaging',
            index=models.Index(fields=['consignment', 'status'], name='pkg_consignment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpackaging',
            index=models.Index(fields=['status', 'is_deleted'], name='pkg_status_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpackaging',
            index=models.Index(fields=['received_date_time'], name='pkg_received_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpackaging',
            index=models.Index(fields=['created_at'], name='pkg_created_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpoline',
            index=models.Index(fields=['consignment'], name='cpl_consignment_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpoline',
            index=models.Index(fields=['purchase_order_line'], name='cpl_po_line_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpoline',
            index=models.Index(fields=['consignment', 'purchase_order_line'], name='cpl_consignment_po_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpoline',
            index=models.Index(fields=['compliance_dg'], name='cpl_compliance_dg_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpoline',
            index=models.Index(fields=['compliance_chemical'], name='cpl_compliance_chemical_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentpoline',
            index=models.Index(fields=['allocated_qty'], name='cpl_allocated_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingallocation',
            index=models.Index(fields=['consignment_packaging', 'purchase_order_line'], name='alloc_pkg_po_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingallocation',
            index=models.Index(fields=['is_dangerous_good'], name='alloc_is_dg_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingallocation',
            index=models.Index(fields=['allocated_qty'], name='alloc_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['reference_number'], name='po_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='po_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['client'], name='po_client_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['storerkey'], name='po_storerkey_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'storerkey', 'is_deleted'], name='po_supplier_storer_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'is_deleted'], name='po_status_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['is_asn', 'status'], name='po_asn_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_type'], name='po_order_type_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_at'], name='po_created_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['purchase_order'], name='pol_po_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['purchase_order', 'status', 'is_deleted'], name='pol_po_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['status'], name='pol_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['status', 'is_deleted'], name='pol_status_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['sku'], name='pol_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['is_dangerous_good'], name='pol_dg_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['is_chemical'], name='pol_chemical_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['open_quantity'], name='pol_open_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['product_code'], name='pol_product_code_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['created_at', 'is_deleted'], name='pol_created_deleted_idx'),
        ),
    ]
