from django.db import models
from .constants import *


class Role(models.TextChoices):
    ADMIN = ADMIN, ADMIN
    SUPPLIER_USER = SUPPLIER_USER, SUPPLIER_USER
    CLIENT_USER = CLIENT_USER, CLIENT_USER
    OPERATIONS = OPERATIONS, OPERATIONS
    

class OperationUserRole(models.TextChoices):
    L1 = L1 , L1
    L2 = L2 , L2
    L3 = L3 , L3

    
class Address(models.TextChoices):
    CLIENT = CLIENT, CLIENT
    SUPPLIER = SUPPLIER, SUPPLIER
    STORERKEY = STORERKEY, STORERKEY


class PackagingTypeChoices(models.TextChoices):
    BOX = BOX, BOX
    PALLET = PALLET, PALLET
    SKID = SKID, SKID
    CONTAINER = CONTAINER, CONTAINER


class DimensionUnitChoices(models.TextChoices):
    CM = CM, CM
    MM = MM, MM
    METER = METER, METER
    INCH = INCH, INCH
    FOOT = FOOT, FOOT
    YARD = YARD, YARD


class WeightUnitChoices(models.TextChoices):
    KILOGRAM = KILOGRAM, KILOGRAM
    GRAM = GRAM, GRAM
    POUND = POUND, POUND
    OUNCE = OUNCE, OUNCE


class ServiceTypeChoices(models.TextChoices):
    THREE_PL = THREE_PL, THREE_PL
    FOUR_PL = FOUR_PL, FOUR_PL


class MeasurementTypeChoices(models.TextChoices):
    IMPERIAL_SYSTEM = IMPERIAL_SYSTEM, IMPERIAL_SYSTEM
    METRIC_SYSTEM = METRIC_SYSTEM, METRIC_SYSTEM
    


class MOTModeChoices(models.TextChoices):
    AIR = AIR, AIR
    LAND = LAND, LAND
    SEA = SEA, SEA


class ConsignmentDocumentTypeChoices(models.TextChoices):
    COMMERCIAL_INVOICE = COMMERCIAL_INVOICE, COMMERCIAL_INVOICE
    DANGEROUS_GOOD= DANGEROUS_GOOD, DANGEROUS_GOOD
    BILL_OF_MATERIAL = BILL_OF_MATERIAL, BILL_OF_MATERIAL
    PACKING_LIST = PACKING_LIST, PACKING_LIST
    MSDS = MSDS, MSDS
    SSDS = SSDS, SSDS
    COMPREHENSIVE_REPORT = COMPREHENSIVE_REPORT, COMPREHENSIVE_REPORT
    

class ConsignmentStatusChoices(models.TextChoices):
    PENDING_FOR_APPROVAL = PENDING_FOR_APPROVAL, PENDING_FOR_APPROVAL
    # PENDING_FF_ASSIGNMENT = PENDING_FF_ASSIGNMENT, PENDING_FF_ASSIGNMENT
    PICKUP_COMPLETED = PICKUP_COMPLETED, PICKUP_COMPLETED
    PENDING_BID = PENDING_BID, PENDING_BID
    # COLLECTION_SCHEDULED = COLLECTION_SCHEDULED, COLLECTION_SCHEDULED
    AT_CUSTOM = AT_CUSTOM, AT_CUSTOM
    CUSTOMS_CLEARED = CUSTOMS_CLEARED, CUSTOMS_CLEARED
    DELIVERED = DELIVERED, DELIVERED
    REJECTED = REJECTED, REJECTED
    CANCELLED = CANCELLED, CANCELLED
    RECEIVED_AT_DESTINATION = RECEIVED_AT_DESTINATION, RECEIVED_AT_DESTINATION
    PENDING_CONSOLE_ASSIGNMENT = PENDING_CONSOLE_ASSIGNMENT, PENDING_CONSOLE_ASSIGNMENT
    FREIGHT_FORWARDER_ASSIGNED = FREIGHT_FORWARDER_ASSIGNED, FREIGHT_FORWARDER_ASSIGNED
    CONSOLE_ASSIGNED = CONSOLE_ASSIGNED, CONSOLE_ASSIGNED
    OUT_FOR_DELIVERY = OUT_FOR_DELIVERY, OUT_FOR_DELIVERY
    PARTIALLY_RECEIVED = PARTIALLY_RECEIVED, PARTIALLY_RECEIVED
    DRAFT = DRAFT, DRAFT
    

class ConsignmentCreationSteps(models.TextChoices):
    STEP_1 = STEP_1, STEP_1
    STEP_2 = STEP_2, STEP_2
    STEP_3 = STEP_3, STEP_3
    STEP_4 = STEP_4, STEP_4
    STEP_5 = STEP_5, STEP_5
    
class PurchaseOrderStatusChoices(models.TextChoices):
    CLOSED = CLOSED, CLOSED
    CANCELLED = CANCELLED, CANCELLED
    OPEN = OPEN, OPEN
    PARTIALLY_FULFILLED = PARTIALLY_FULFILLED, PARTIALLY_FULFILLED
    
    
class ConsoleStatusChoices(models.TextChoices):
    IN_TRANSIT = IN_TRANSIT, IN_TRANSIT
    AT_CUSTOM = AT_CUSTOM, AT_CUSTOM
    DELIVERED = DELIVERED, DELIVERED
    NEW = NEW, NEW
    FREIGHT_FORWARDER_ASSIGNED = FREIGHT_FORWARDER_ASSIGNED, FREIGHT_FORWARDER_ASSIGNED
    PICKUP_REJECTED = PICKUP_REJECTED,PICKUP_REJECTED
    PARTIALLY_RECEIVED = PARTIALLY_RECEIVED, PARTIALLY_RECEIVED
    PARTIALLY_DELIVERED = PARTIALLY_DELIVERED, PARTIALLY_DELIVERED
    RECEIVED_AT_DESTINATION = RECEIVED_AT_DESTINATION, RECEIVED_AT_DESTINATION
    CANCELLED = CANCELLED, CANCELLED

    

class ConsignmentTypeChoices(models.TextChoices):
    PO_BASED = PO_BASED, PO_BASED
    ADHOC = ADHOC, ADHOC
    OBD_IBD = OBD_IBD, OBD_IBD
    

class POUploadStatusChoices(models.TextChoices):
    SUCCESS = SUCCESS, SUCCESS
    ERROR = ERROR, ERROR
    IN_PROGRESS = IN_PROGRESS, IN_PROGRESS
    FAILED = FAILED, FAILED
    QUEUE = QUEUE, QUEUE


class UserGridPreferences(models.TextChoices):
    CONSIGNMENT = CONSIGNMENT,CONSIGNMENT
    PURCHASE_ORDER = PURCHASE_ORDER ,PURCHASE_ORDER
    CLIENT_CONFIGURATION = CLIENT_CONFIGURATION,CLIENT_CONFIGURATION
    OPERATION_USER_CONFIGURATION = OPERATION_USER_CONFIGURATION,OPERATION_USER_CONFIGURATION
    HUB_CONFIGURATION = HUB_CONFIGURATION,HUB_CONFIGURATION
    SUPPLIER_CONFIGURATION = SUPPLIER_CONFIGURATION, SUPPLIER_CONFIGURATION
    STORER_CONFIGURATION = STORER_CONFIGURATION,STORER_CONFIGURATION
    MOT_CONFIGURATION = MOT_CONFIGURATION,MOT_CONFIGURATION
    FF_CONFIGURATION =FF_CONFIGURATION,FF_CONFIGURATION
    GL_ACC_CONFIGURATION =GL_ACC_CONFIGURATION,GL_ACC_CONFIGURATION
    COST_CENTER_CODE_CONFIGURATION=COST_CENTER_CODE_CONFIGURATION,COST_CENTER_CODE_CONFIGURATION
    REJECTION_CODE_CONFIGURATION =REJECTION_CODE_CONFIGURATION,REJECTION_CODE_CONFIGURATION
    
    
class ShipmentTypeChoices(models.TextChoices):
    International_Freight = International_Freight,International_Freight
    Inbound_Freight_And_Handling = Inbound_Freight_And_Handling,Inbound_Freight_And_Handling
    Freight_Related_Expenses = Freight_Related_Expenses,Freight_Related_Expenses
    Outbound_Freight = Outbound_Freight,Outbound_Freight

class NotificationChoices(models.TextChoices):
    CONSIGNMENT = CONSIGNMENT, CONSIGNMENT
    PURCHASE_ORDER = PURCHASE_ORDER, PURCHASE_ORDER
    CONSOLE = CONSOLE, CONSOLE
    EXPEDITING = EXPEDITING, EXPEDITING
    PO_FILE_UPLOAD = PO_FILE_UPLOAD, PO_FILE_UPLOAD
    COMPREHENSIVE_REPORT = COMPREHENSIVE_REPORT, COMPREHENSIVE_REPORT


class PackageStatusChoices(models.TextChoices):
    NOT_RECEIVED = NOT_RECEIVED, NOT_RECEIVED
    RECEIVED = RECEIVED, RECEIVED
    DRAFT = DRAFT, DRAFT,
    PO_LINES = PO_LINES, PO_LINES, # This is for internal use only to store the PO lines for a consignment
    DELIVERED = DELIVERED, DELIVERED
    CANCELLED = CANCELLED, CANCELLED

class GLCodeChoices(models.TextChoices):
    CODE_56000100 = CODE_56000100, CODE_56000100 ## If ship from and ship to are same
    CODE_56010000 = CODE_56010000, CODE_56010000 ## If ship from and ship to are not same


class OrderTypeChoices(models.TextChoices):
    BTS = BTS, BTS
    BTO = BTO, BTO
    BOTH = BOTH, BOTH


class POImportFormatsChoices(models.TextChoices):
    PO = PO, PO
    SLB = SLB, SLB