# Generated by Django 5.1.6 on 2025-06-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hub',
            options={},
        ),
        migrations.AlterModelOptions(
            name='operations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storerkey',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplieruser',
            options={},
        ),
    ]
