# Generated by Django 5.1.6 on 2025-06-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_client_options_alter_clientuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='access_level',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], default='L3', max_length=50),
        ),
    ]
