# Generated by Django 5.0.14 on 2025-06-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_operations_access_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='clientuser',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='hub',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='operations',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='storerkey',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='supplieruser',
            options={'ordering': ('id',)},
        ),
    ]
