# Generated by Django 5.0.14 on 2025-06-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_alter_client_options_alter_clientuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hub',
            options={},
        ),
        migrations.AlterModelOptions(
            name='operations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storerkey',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplieruser',
            options={},
        ),
    ]
