# Generated by Django 5.0.14 on 2025-08-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_client_options_alter_clientuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='eccn_validation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='generate_asn',
        ),
        migrations.RemoveField(
            model_name='client',
            name='hs_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='hs_code_validation',
        ),
        migrations.AddField(
            model_name='storerkey',
            name='adhoc_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storerkey',
            name='chemical_good_handling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storerkey',
            name='eccn_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storerkey',
            name='expediting_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storerkey',
            name='generate_asn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storerkey',
            name='hs_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storerkey',
            name='hs_code_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storerkey',
            name='reminder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storerkey',
            name='trigger_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
