# Generated by Django 5.0.14 on 2025-08-14 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_remove_client_eccn_validation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerousGood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('un_class', models.CharField(max_length=128)),
                ('un_category', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('un_class', 'un_category')},
            },
        ),
    ]
