# Generated by Django 5.2.5 on 2025-08-18 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_dangerousgood'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=128, unique=True)),
                ('is_chemical', models.BooleanField(default=False)),
                ('is_dangerous_good', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(max_length=128)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('hs_code', models.CharField(blank=True, max_length=128, null=True)),
                ('stock_number', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('alternate_unit', models.CharField(blank=True, max_length=128, null=True)),
                ('alternate_sku', models.CharField(blank=True, max_length=128, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=50, null=True)),
                ('to_expire_days', models.PositiveSmallIntegerField(default=0)),
                ('to_delivery_days', models.PositiveSmallIntegerField(default=0)),
                ('to_best_by_days', models.PositiveSmallIntegerField(default=0)),
                ('is_kit', models.BooleanField(default=False)),
                ('is_stackable', models.BooleanField(default=False)),
                ('inspection_required', models.BooleanField(default=False)),
                ('shelf_life', models.PositiveSmallIntegerField(default=0)),
                ('shelf_life_indicator', models.CharField(blank=True, max_length=256, null=True)),
                ('sku_class', models.CharField(blank=True, max_length=256, null=True)),
                ('retail_sku', models.CharField(blank=True, max_length=256, null=True)),
                ('hazmat_codes_keys', models.CharField(blank=True, max_length=256, null=True)),
                ('susr1', models.CharField(blank=True, max_length=256, null=True)),
                ('susr2', models.CharField(blank=True, max_length=256, null=True)),
                ('susr3', models.CharField(blank=True, max_length=256, null=True)),
                ('susr4', models.CharField(blank=True, max_length=256, null=True)),
                ('susr5', models.CharField(blank=True, max_length=256, null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_master', to='entities.hub')),
                ('storerkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_master', to='entities.storerkey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
