# Generated by Django 5.2.5 on 2025-08-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_materialmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmaster',
            name='uom',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
