# Generated by Django 5.2.5 on 2025-08-18 11:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_materialmaster_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storerkey',
            name='reminder_name',
        ),
        migrations.RemoveField(
            model_name='storerkey',
            name='trigger_days',
        ),
        migrations.CreateModel(
            name='StorerKeyReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_name', models.CharField(max_length=200)),
                ('trigger_days', models.IntegerField(default=0)),
                ('storerkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='entities.storerkey')),
            ],
            options={
                'unique_together': {('storerkey', 'reminder_name')},
            },
        ),
    ]
