# Generated by Django 5.2.5 on 2025-08-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_remove_storerkey_reminder_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storerkeyreminder',
            old_name='reminder_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='storerkeyreminder',
            unique_together={('storerkey', 'name')},
        ),
    ]
