# Generated by Django 5.2.5 on 2025-09-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_rename_reminder_name_storerkeyreminder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerkey',
            name='order_type',
            field=models.CharField(choices=[('BTS', 'BTS'), ('BTO', 'BTO')], default='BTS', max_length=5),
        ),
    ]
