# Generated by Django 5.2.5 on 2025-09-03 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_storerkey_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerousGoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DangerousGoodClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DangerousGood',
        ),
        migrations.AddField(
            model_name='dangerousgoodcategory',
            name='dg_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='entities.dangerousgoodclass'),
        ),
    ]
