# Generated by Django 5.2.5 on 2025-09-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0013_dangerousgoodcategory_dangerousgoodclass_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DangerousGoodCategory',
        ),
        migrations.DeleteModel(
            name='DangerousGoodClass',
        ),
    ]
