# Generated by Django 5.2.5 on 2025-09-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_dangerousgoodclass_dangerousgoodcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangerousgoodclass',
            name='code',
        ),
    ]
