# Generated by Django 5.2.5 on 2025-10-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_remove_dangerousgoodclass_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmaster',
            name='product_code',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='materialmaster',
            unique_together={('product_code', 'storerkey', 'hub')},
        ),
    ]
