# Generated by Django 5.2.5 on 2025-11-10 06:23

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0017_alter_materialmaster_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerkey',
            name='aramex_wms_storerkey',
            field=models.CharField(default=datetime.datetime(2025, 11, 10, 6, 22, 39, 597053, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerkey',
            name='can_add_shipto_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storerkey',
            name='measurement_method',
            field=models.CharField(choices=[('Imperial System', 'Imperial System'), ('Metric System', 'Metric System')], default=datetime.datetime(2025, 11, 10, 6, 22, 46, 490788, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerkey',
            name='service_type',
            field=models.CharField(choices=[('3PL', '3PL'), ('4PL', '4PL')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerkey',
            name='show_parent_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storerkey',
            name='timezone',
            field=models.CharField(default='SLB', max_length=255),
            preserve_default=False,
        ),
    ]
