# Generated by Django 5.2.5 on 2025-11-10 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0018_storerkey_aramex_wms_storerkey_and_more'),
        ('portal', '0030_alter_costcentercode_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerkey',
            name='cc_code',
            field=models.ForeignKey(
                to='portal.costcentercode',
                on_delete=django.db.models.deletion.RESTRICT,
                null=True,
                blank=True,
                related_name='storerkeys',
            ),
        )
    ]
