# Generated by Django 5.2.5 on 2025-11-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0019_storerkey_cc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storerkey',
            name='order_type',
            field=models.CharField(choices=[('BTS', 'BTS'), ('BTO', 'BTO'), ('Both', 'Both')], default='BTS', max_length=5),
        ),
    ]
