# Generated by Django 5.2.5 on 2025-11-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_alter_storerkey_measurement_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storerkey',
            name='measurement_method',
        ),
    ]
