# Generated by Django 5.2.5 on 2025-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0022_remove_storerkey_measurement_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerkey',
            name='measurement_method',
            field=models.CharField(choices=[('Imperial System', 'Imperial System'), ('Metric System', 'Metric System')], default='Imperial System', max_length=50),
        ),
    ]
