# Generated by Django 5.2.5 on 2025-12-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0023_storerkey_measurement_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='can_add_shipto_add',
        ),
        migrations.RemoveField(
            model_name='client',
            name='measurement_method',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='show_parent_add',
        ),
        migrations.RemoveField(
            model_name='client',
            name='timezone',
        ),
    ]
