# Generated by Django 5.2.5 on 2025-12-10 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0024_remove_client_can_add_shipto_add_and_more'),
        ('portal', '0037_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_code'], name='client_code_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='client_name_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='client_active_idx'),
        ),
        migrations.AddIndex(
            model_name='clientuser',
            index=models.Index(fields=['client'], name='cu_client_idx'),
        ),
        migrations.AddIndex(
            model_name='clientuser',
            index=models.Index(fields=['user'], name='cu_user_idx'),
        ),
        migrations.AddIndex(
            model_name='clientuser',
            index=models.Index(fields=['is_active'], name='cu_active_idx'),
        ),
        migrations.AddIndex(
            model_name='clientuser',
            index=models.Index(fields=['client', 'is_active'], name='cu_client_active_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmaster',
            index=models.Index(fields=['storerkey'], name='mm_storerkey_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmaster',
            index=models.Index(fields=['hub'], name='mm_hub_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmaster',
            index=models.Index(fields=['product_code'], name='mm_product_code_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmaster',
            index=models.Index(fields=['is_dangerous_good'], name='mm_dg_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmaster',
            index=models.Index(fields=['is_chemical'], name='mm_chemical_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmaster',
            index=models.Index(fields=['storerkey', 'product_code'], name='mm_storerkey_product_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmaster',
            index=models.Index(fields=['is_stackable'], name='mm_stackable_idx'),
        ),
        migrations.AddIndex(
            model_name='storerkey',
            index=models.Index(fields=['storerkey_code'], name='sk_code_idx'),
        ),
        migrations.AddIndex(
            model_name='storerkey',
            index=models.Index(fields=['client'], name='sk_client_idx'),
        ),
        migrations.AddIndex(
            model_name='storerkey',
            index=models.Index(fields=['hub'], name='sk_hub_idx'),
        ),
        migrations.AddIndex(
            model_name='storerkey',
            index=models.Index(fields=['client', 'hub'], name='sk_client_hub_idx'),
        ),
        migrations.AddIndex(
            model_name='storerkey',
            index=models.Index(fields=['hs_code_validation'], name='sk_hs_idx'),
        ),
        migrations.AddIndex(
            model_name='storerkey',
            index=models.Index(fields=['chemical_good_handling'], name='sk_chemical_idx'),
        ),
        migrations.AddIndex(
            model_name='storerkey',
            index=models.Index(fields=['is_active'], name='sk_active_idx'),
        ),
        migrations.AddIndex(
            model_name='storerkey',
            index=models.Index(fields=['order_type'], name='sk_order_type_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_code'], name='supplier_code_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['client'], name='supplier_client_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='supplier_name_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='supplier_active_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['client', 'is_active'], name='supplier_client_active_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['created_at'], name='supplier_created_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieruser',
            index=models.Index(fields=['supplier'], name='su_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieruser',
            index=models.Index(fields=['user'], name='su_user_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieruser',
            index=models.Index(fields=['is_active'], name='su_active_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieruser',
            index=models.Index(fields=['supplier', 'is_active'], name='su_supplier_active_idx'),
        ),
    ]
