from rest_framework.views import APIView
from django.core.exceptions import ValidationError
from django.db import transaction
from core.response import StandardResponse
from .models import Console, XML
from portal.utils import render_to_pdf, render_to_xml, render_to_html
from operations.models import Consignment, PackagingAllocation
import base64
import os
from django.conf import settings
from django.utils import timezone
from django.utils._os import safe_join
from .services import BOLServices
from django.db.models import Subquery, OuterRef, Sum
from collections import defaultdict


# def generate_base_bol(request, console_id=None):
    
#     consignment_id = request.GET.get("consignment_id")

#     try:
#         console = Console.objects.get(console_id=console_id)
#         consignment = Consignment.objects.select_related("bol","purchase_order").get(consignment_id=consignment_id, console=console)
#     except Console.DoesNotExist:
#         return StandardResponse(status=400, success=False, errors=["Console Object not found"])
#     except Consignment.DoesNotExist:
#         return StandardResponse(status=400, success=False, errors=["Console Object not found"])


#     output_dir = os.path.join(settings.MEDIA_ROOT, 'bols')
#     os.makedirs(output_dir, exist_ok=True)

#     logo_path = os.path.join(settings.BASE_DIR, 'static', 'aramerlogo.png')
#     try:
#         with open(logo_path, 'rb') as img_file:
#             logo_base64 = base64.b64encode(img_file.read()).decode('utf-8')
#     except Exception as e:
#         return StandardResponse(status=500, success=False, errors=[f"Error loading logo: {e}"])

#     return console, consignment, output_dir, logo_base64


# def update_console_consignment_bol_gen(user,console,consignment):
#         last_bol_generated_at = timezone.now()

#         console.last_bol_generated_at = last_bol_generated_at
#         console.last_bol_generated_by = user
#         console.save()

#         # Update console
#         consignment.last_bol_gen_at = last_bol_generated_at
#         consignment.last_bol_gen_by = user
#         consignment.save()


# def bol_context(consignment,serialized,logo_base64):

#     context = {
#         'logo_base64': logo_base64,
#         'sku_data': serialized.get("sku_data"),
#         "ship_from": serialized.get("ship_from"),
#         "ship_to": serialized.get("ship_to"),
#         "carrier_name": serialized.get("freight_forwarder", {}).get("name"),
#         "consignment_id": consignment.consignment_id,
#         "po_number" : consignment.purchase_order.customer_reference_number,
#         "cc_code": get_cc_code(consignment.purchase_order.plant_id,consignment.purchase_order.center_code),
#         "gl_account": generate_gl_code(consignment),
#         "packages": serialized.get("packages"),
#         "bol": serialized,
#     }

#     return context




# class BOLGenerateAPI(APIView):

#     def get(self, request, console_id=None, *args, **kwargs):

#         console, consignment, output_dir, logo_base64 = generate_base_bol(request, console_id=console_id)

#         filenames = []

#         def generate_pdf_from_bol(consignment):
#             serialized = BOLGenerateSerializer(consignment.bol).data
            
#             context = bol_context(consignment,serialized,logo_base64)

#             filename = f"bol_{serialized['bol_id']}.pdf"
#             output_path = safe_join(output_dir, filename)
#             render_to_pdf("pdf_template.html", context, output_path=output_path)
#             return f"/media/bols/{filename}"

#         try:

#             if consignment:
#             # try:
#             #     consignment = Consignment.objects.select_related("bol","purchase_order").get(consignment_id=consignment_id, console=console)
#             # except Consignment.DoesNotExist:
#             #     return StandardResponse(status=400, success=False, errors=["Consignment Object not found"])
#                 if not consignment.bol:
#                     return StandardResponse(status=400, success=False, errors=["BOL not found for given consignment"])
#                 filenames.append(generate_pdf_from_bol(consignment))
#             # else:
#             #     bols = BOL.objects.filter(console=console, is_bol_locked=False).select_related()
#             #     for bol in bols:
#             #         consignment = Consignment.objects.filter(bol= bol,console=console).first()
#             #         filenames.append(generate_pdf_from_bol(consignment))

#         except Exception as e:
#             return StandardResponse(status=500, success=False, errors=[str(e)])

#         user = getattr(request, "this_user", None)
        
#         ## Update last_generated by for consignment and console
#         update_console_consignment_bol_gen(user,console,consignment)

#         ## bol generation log
#         log_bol_generation(user,console,consignment, filenames)

#         return StandardResponse(status=200, data=filenames)
    
# class BOLGenerateHTMLAPI(APIView):
#     def get(self, request, console_id=None, *args, **kwargs):

#         console, consignment, output_dir, logo_base64 = generate_base_bol(request, console_id=console_id)

#         html_outputs = []

#         def generate_html_from_bol(consignment):
#             serialized = BOLGenerateSerializer(consignment.bol).data

#             context = bol_context(consignment,serialized,logo_base64)
            
#             filename = f"bol_{serialized['bol_id']}.pdf"
#             output_path = safe_join(output_dir, filename)
#             html = render_to_html("pdf_template.html", context)            
#             return html

#         try:
#             if consignment:
#                 # try:
#                 #     consignment = Consignment.objects.select_related("bol").get(consignment_id=consignment_id, console=console)
#                 # except Consignment.DoesNotExist:
#                 #     return StandardResponse(status=400, success=False, errors=["Consignment Object not found"])
#                 if not consignment.bol:
#                     return StandardResponse(status=400, success=False, errors=["BOL not found for given consignment"])
#                 html_outputs.append(generate_html_from_bol(consignment))
#             # else:
#             #     bols = BOL.objects.filter(console=console, is_bol_locked=False).select_related()
#             #     for bol in bols:
#             #         con = Consignment.objects.filter(bol= bol,console=console).first()
#             #         html_outputs.append(generate_html_from_bol(con))

#         except Exception as e:
#             return StandardResponse(status=500, success=False, errors=[str(e)])

#         user = getattr(request, "this_user", None)
        
#         ## Update last_generated by for consignment and console
#         update_console_consignment_bol_gen(user,console,consignment)

#         ## bol generation log
#         log_bol_generation(user, console, consignment, html_outputs)

#         # Return the HTML(s) directly
#         if len(html_outputs) == 1:
#             return StandardResponse(status=200, data=html_outputs[0])
#         else:
#             # If multiple, return as a joined HTML (or could be a JSON array)
#             return StandardResponse(status=200, data="<hr/>".join(html_outputs))


class BOLGenerateHTMLV2API(APIView):
     def get(self, request, id=None, *args, **kwargs):
        
        try:
            if not id:
                return StandardResponse(status=400, success=False, errors=["consignment id is required"])
            
            consignment = Consignment.objects.select_related("console").get(consignment_id=id)
            console = consignment.console

            if not console:
                return StandardResponse(status=404, success=False, errors=["Can't generate BOL for the given consignment, Console not found."])

            output_dir = os.path.join(settings.MEDIA_ROOT, 'bols')
            os.makedirs(output_dir, exist_ok=True)

            logo_path = os.path.join(settings.BASE_DIR, 'static', 'aramexlogo.png')

            with open(logo_path, 'rb') as img_file:
                logo_base64 = base64.b64encode(img_file.read()).decode('utf-8')
            
            html_outputs = []
            
            # serialized = BOLServices.serialized_bol_data(consignment=consignment)

            # context = BOLServices.bol_context(consignment,serialized,logo_base64)

            context = BOLServices.bol_context_data(consignment=consignment, logo_base64=logo_base64)
            
            filename = f"bol_{consignment.consignment_id}.pdf"
            output_path = safe_join(output_dir, filename)
            html = render_to_html("pdf_template.html", context)   
            html_outputs.append(html)         

            user = getattr(request, "this_user", None)

            BOLServices.update_console_consignment_bol_gen(user,console,consignment)

            BOLServices.log_bol_generation(user, console, consignment, html_outputs)

            if len(html_outputs) == 1:
                return StandardResponse(status=200, data=html_outputs[0])
            else:
                return StandardResponse(status=200, data="<hr/>".join(html_outputs))
        
        except Exception as e:
            return StandardResponse(status=500, success=False, errors=[str(e)])
        except Consignment.DoesNotExist:
            return StandardResponse(status=404, success=False, errors="Invalid consignment ID")
        except Exception as e:
                return StandardResponse(status=500, success=False, errors=[f"Error loading logo: {e}"])
        


class ConsoleBOL(APIView):
     def get(self, request, id=None, *args, **kwargs):
        
        try:
            if not id:
                return StandardResponse(status=400, success=False, errors=["console id is required"])
            
            console = Console.objects.prefetch_related("consignments").filter(console_id=id).first()
            if not console:
                return StandardResponse(status=404, success=False, errors=["Can't generate BOL for the given console, Console not found."])

            consignments = console.consignments.all()
            if not consignments:
                return StandardResponse(status=404, success=False, errors=["Please add the consignments first"])
            
            
            output_dir = os.path.join(settings.MEDIA_ROOT, 'bols')
            os.makedirs(output_dir, exist_ok=True)

            logo_path = os.path.join(settings.BASE_DIR, 'static', 'aramexlogo.png')

            with open(logo_path, 'rb') as img_file:
                logo_base64 = base64.b64encode(img_file.read()).decode('utf-8')
            
            html_outputs = []
            
            grouped = defaultdict(list)

            for c in consignments:
                key = (c.supplier, c.consignor_address, c.delivery_address)
                grouped[key].append(c)

            context = []
            for i, (key, value) in enumerate(grouped.items(), start=1):
                data = BOLServices.console_bol_context_data(
                    consignments=value,
                    logo_base64=logo_base64
                )
                data["bill_of_lading_id"] = f"{console.console_id}-{i}"
                context.append(data)

            filename = f"bol_{console.console_id}.pdf"
            output_path = safe_join(output_dir, filename)
            html = render_to_html("multi_pdf_template.html", {"context" : context})   
            html_outputs.append(html)         

            user = getattr(request, "this_user", None)

            # BOLServices.update_console_consignment_bol_gen(user,console,consignments.first())

            BOLServices.log_bol_generation(user, console, list(consignments), html_outputs)

            if len(html_outputs) == 1:
                return StandardResponse(status=200, data=html_outputs[0])
            else:
                return StandardResponse(status=200, data="<hr/>".join(html_outputs))
        
        except Exception as e:
            return StandardResponse(status=500, success=False, errors=[str(e)])
        except Consignment.DoesNotExist:
            return StandardResponse(status=404, success=False, errors="Invalid consignment ID")
        except Exception as e:
                return StandardResponse(status=500, success=False, errors=[f"Error loading logo: {e}"])
        
        



class XMLGenerateAPI(APIView):

    def to_representation(self, consignments):

        representation = []
        for consignment in consignments:
            data = {}
            data["bol_id"] = consignment.consignment_id
            data["gl_code"] = consignment.gl_code or None
            data["ship_from"] = {
                "supplier_name" : consignment.supplier.name or None,
                "address_line_1" : consignment.consignor_address.address_line_1 or None,
                "address_line_2" : consignment.consignor_address.address_line_2 or None,
                "city" : consignment.consignor_address.city or None,
                "state" : consignment.consignor_address.state or None,
                "zipcode" : consignment.consignor_address.zipcode or None,
                "country" : consignment.consignor_address.country or None,
            }

            data["ship_to"] = {
                "client_name" : consignment.client.name or None,
                "address_line_1" : consignment.delivery_address.address_line_1 or None,
                "address_line_2" : consignment.delivery_address.address_line_2 or None,
                "city" : consignment.delivery_address.city or None,
                "state" : consignment.delivery_address.state or None,
                "zipcode" : consignment.delivery_address.zipcode or None,
                "country" : consignment.delivery_address.country or None,
            }
            
            po_lines = consignment.purchase_order_lines.all().select_related("purchase_order").distinct()
            
            # Subquery to sum allocated_qty per PO line for this consignment
            allocated_qty_subquery = (
                PackagingAllocation.objects
                .filter(
                    purchase_order_line_id=OuterRef("id"),
                    consignment_packaging__consignment=consignment
                )
                .values("purchase_order_line_id")
                .annotate(total_allocated=Sum("allocated_qty"))
                .values("total_allocated")[:1]
            )

            # Query PO lines efficiently
            po_line_values = (
                po_lines
                .annotate(allocated_qty=Subquery(allocated_qty_subquery))
                .values(
                    "reference_number",
                    "customer_reference_number",
                    "product_code",
                    "description",
                    "purchase_order__plant_id",
                    "purchase_order__center_code",
                    "allocated_qty",
                )
            )

            # Compute cc_code in Python
            po_line_data = []
            for line in po_line_values:
                cc_code = BOLServices.get_cc_code(
                    line["purchase_order__plant_id"], 
                    line["purchase_order__center_code"]
                )
                line["cc_code"] = cc_code
                po_line_data.append(line)

            data["po_lines"] = po_line_data
            
            representation.append(data)
        return representation
    

    def get(self, request, console_id=None, *args, **kwargs):
        try:
            console = Console.objects.get(console_id=console_id) 
        except (Console.DoesNotExist, ValidationError):
            return StandardResponse(status=400, success=False, errors=["Object not found"])
        
        # if console.console_status != ConsoleStatusChoices.DELIVERED:
        #     return StandardResponse(status=400, success=False, errors=["Console is not delivered hence, XML can't be generated"])
        
        consignments = Consignment.objects.filter(console=console).select_related("supplier","client","consignor_address","delivery_address").prefetch_related("purchase_order_lines","console__freight_forwarder")
    
        if not consignments.exists():
            return StandardResponse(status=404, success=False, errors=["No consignments found"])
        
        serialized_data = self.to_representation(consignments)

        
        # all_bols = BOL.objects.filter(console=console)
        # serialized_data = XMLGnerateSerializer(all_bols, many=True).data

        output_dir = os.path.join(settings.MEDIA_ROOT, 'xml')
        os.makedirs(output_dir, exist_ok=True)

        filename = f"xml_{console_id}.xml"
        output_path = os.path.join(output_dir, filename)
        file_path = "/media/xml/"+filename

        context = {
            "bill_of_ladings": serialized_data
        }
        render_to_xml("xml_template.xml", context, output_path=output_path)
        
        # all_bols.update(is_bol_locked=True)
        xml = XML.objects.create(generated_by=request.this_user, file_path=file_path)
        
        Consignment.objects.filter(console=console).update(xml=xml)
        
        return StandardResponse(status=200, data=file_path)   
    
